//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.Photos = new HashSet<Photos>();
        }
    
        public int orderId { get; set; }
        public string pacageId { get; set; }
        public Nullable<System.DateTime> dateOrder { get; set; }
        public int numberOfOurs { get; set; }
        public Nullable<bool> Publishable { get; set; }
        public int userId { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        public virtual pakages pakages { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Photos> Photos { get; set; }
    }
}
