//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int orderId { get; set; }
        public string pacageId { get; set; }
        public Nullable<System.DateTime> dateOrder { get; set; }
        public int numberOfOurs { get; set; }
        public Nullable<bool> Publishable { get; set; }
        public int userId { get; set; }
    }
}
