//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PhotoDBChasiLeaEntities : DbContext
    {
        public PhotoDBChasiLeaEntities()
            : base("name=PhotoDBChasiLeaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<pakages> pakages { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Photos> Photos { get; set; }
    }
}
